/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdministratorRouteImport } from './routes/admin.administrator'
import { Route as AdminCustomerServiceRouteImport } from './routes/admin.customer-service'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDepositRequestsRouteImport } from './routes/admin.deposit-requests'
import { Route as AdminFinancialStatusRouteImport } from './routes/admin.financial-status'
import { Route as AdminFuturesRouteImport } from './routes/admin.futures'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminOwnershipRouteImport } from './routes/admin.ownership'
import { Route as AdminSampleTokensRouteImport } from './routes/admin.sample-tokens'
import { Route as AdminSpotControlRouteImport } from './routes/admin.spot-control'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppEarnRouteImport } from './routes/app.earn'
import { Route as AppFaqRouteImport } from './routes/app.faq'
import { Route as AppFuturesRouteImport } from './routes/app.futures'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppPoliciesRouteImport } from './routes/app.policies'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSpotRouteImport } from './routes/app.spot'
import { Route as AppTermsRouteImport } from './routes/app.terms'
import { Route as AppTradeFiRouteImport } from './routes/app.trade-fi'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesFeesRouteImport } from './routes/guides.fees'
import { Route as GuidesGettingStartedRouteImport } from './routes/guides.getting-started'
import { Route as GuidesSecurityRouteImport } from './routes/guides.security'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsSymbolRouteImport } from './routes/markets.$symbol'
import { Route as TradingIndexRouteImport } from './routes/trading.index'
import { Route as TradingFuturesRouteImport } from './routes/trading.futures'
import { Route as TradingSpotRouteImport } from './routes/trading.spot'
import { Route as ApiPublicAdminDeleteRouteImport } from './routes/api/public/admin.delete'
import { Route as ApiPublicAdminRegisterRouteImport } from './routes/api/public/admin.register'
import { Route as ApiPublicAdminUpdateRouteImport } from './routes/api/public/admin.update'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministratorRoute = AdminAdministratorRouteImport.update({
  id: '/administrator',
  path: '/administrator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerServiceRoute = AdminCustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositRequestsRoute = AdminDepositRequestsRouteImport.update({
  id: '/deposit-requests',
  path: '/deposit-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialStatusRoute = AdminFinancialStatusRouteImport.update({
  id: '/financial-status',
  path: '/financial-status',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFuturesRoute = AdminFuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOwnershipRoute = AdminOwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSampleTokensRoute = AdminSampleTokensRouteImport.update({
  id: '/sample-tokens',
  path: '/sample-tokens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpotControlRoute = AdminSpotControlRouteImport.update({
  id: '/spot-control',
  path: '/spot-control',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppEarnRoute = AppEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => AppRoute,
} as any)
const AppFaqRoute = AppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppRoute,
} as any)
const AppFuturesRoute = AppFuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRoute = AppPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSpotRoute = AppSpotRouteImport.update({
  id: '/spot',
  path: '/spot',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppTradeFiRoute = AppTradeFiRouteImport.update({
  id: '/trade-fi',
  path: '/trade-fi',
  getParentRoute: () => AppRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFeesRoute = GuidesFeesRouteImport.update({
  id: '/guides/fees',
  path: '/guides/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGettingStartedRoute = GuidesGettingStartedRouteImport.update({
  id: '/guides/getting-started',
  path: '/guides/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSecurityRoute = GuidesSecurityRouteImport.update({
  id: '/guides/security',
  path: '/guides/security',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsSymbolRoute = MarketsSymbolRouteImport.update({
  id: '/markets/$symbol',
  path: '/markets/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingIndexRoute = TradingIndexRouteImport.update({
  id: '/trading/',
  path: '/trading/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingFuturesRoute = TradingFuturesRouteImport.update({
  id: '/trading/futures',
  path: '/trading/futures',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingSpotRoute = TradingSpotRouteImport.update({
  id: '/trading/spot',
  path: '/trading/spot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminDeleteRoute = ApiPublicAdminDeleteRouteImport.update({
  id: '/api/public/admin/delete',
  path: '/api/public/admin/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminRegisterRoute = ApiPublicAdminRegisterRouteImport.update({
  id: '/api/public/admin/register',
  path: '/api/public/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminUpdateRoute = ApiPublicAdminUpdateRouteImport.update({
  id: '/api/public/admin/update',
  path: '/api/public/admin/update',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/policies': typeof PoliciesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/administrator': typeof AdminAdministratorRoute
  '/admin/customer-service': typeof AdminCustomerServiceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposit-requests': typeof AdminDepositRequestsRoute
  '/admin/financial-status': typeof AdminFinancialStatusRoute
  '/admin/futures': typeof AdminFuturesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ownership': typeof AdminOwnershipRoute
  '/admin/sample-tokens': typeof AdminSampleTokensRoute
  '/admin/spot-control': typeof AdminSpotControlRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/earn': typeof AppEarnRoute
  '/app/faq': typeof AppFaqRoute
  '/app/futures': typeof AppFuturesRoute
  '/app/home': typeof AppHomeRoute
  '/app/market': typeof AppMarketRoute
  '/app/policies': typeof AppPoliciesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spot': typeof AppSpotRoute
  '/app/terms': typeof AppTermsRoute
  '/app/trade-fi': typeof AppTradeFiRoute
  '/guides/fees': typeof GuidesFeesRoute
  '/guides/getting-started': typeof GuidesGettingStartedRoute
  '/guides/security': typeof GuidesSecurityRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/trading/futures': typeof TradingFuturesRoute
  '/trading/spot': typeof TradingSpotRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/trading/': typeof TradingIndexRoute
  '/api/public/admin/delete': typeof ApiPublicAdminDeleteRoute
  '/api/public/admin/register': typeof ApiPublicAdminRegisterRoute
  '/api/public/admin/update': typeof ApiPublicAdminUpdateRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/policies': typeof PoliciesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/administrator': typeof AdminAdministratorRoute
  '/admin/customer-service': typeof AdminCustomerServiceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposit-requests': typeof AdminDepositRequestsRoute
  '/admin/financial-status': typeof AdminFinancialStatusRoute
  '/admin/futures': typeof AdminFuturesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ownership': typeof AdminOwnershipRoute
  '/admin/sample-tokens': typeof AdminSampleTokensRoute
  '/admin/spot-control': typeof AdminSpotControlRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/earn': typeof AppEarnRoute
  '/app/faq': typeof AppFaqRoute
  '/app/futures': typeof AppFuturesRoute
  '/app/home': typeof AppHomeRoute
  '/app/market': typeof AppMarketRoute
  '/app/policies': typeof AppPoliciesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spot': typeof AppSpotRoute
  '/app/terms': typeof AppTermsRoute
  '/app/trade-fi': typeof AppTradeFiRoute
  '/guides/fees': typeof GuidesFeesRoute
  '/guides/getting-started': typeof GuidesGettingStartedRoute
  '/guides/security': typeof GuidesSecurityRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/trading/futures': typeof TradingFuturesRoute
  '/trading/spot': typeof TradingSpotRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/markets': typeof MarketsIndexRoute
  '/trading': typeof TradingIndexRoute
  '/api/public/admin/delete': typeof ApiPublicAdminDeleteRoute
  '/api/public/admin/register': typeof ApiPublicAdminRegisterRoute
  '/api/public/admin/update': typeof ApiPublicAdminUpdateRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/policies': typeof PoliciesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/administrator': typeof AdminAdministratorRoute
  '/admin/customer-service': typeof AdminCustomerServiceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposit-requests': typeof AdminDepositRequestsRoute
  '/admin/financial-status': typeof AdminFinancialStatusRoute
  '/admin/futures': typeof AdminFuturesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ownership': typeof AdminOwnershipRoute
  '/admin/sample-tokens': typeof AdminSampleTokensRoute
  '/admin/spot-control': typeof AdminSpotControlRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/earn': typeof AppEarnRoute
  '/app/faq': typeof AppFaqRoute
  '/app/futures': typeof AppFuturesRoute
  '/app/home': typeof AppHomeRoute
  '/app/market': typeof AppMarketRoute
  '/app/policies': typeof AppPoliciesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spot': typeof AppSpotRoute
  '/app/terms': typeof AppTermsRoute
  '/app/trade-fi': typeof AppTradeFiRoute
  '/guides/fees': typeof GuidesFeesRoute
  '/guides/getting-started': typeof GuidesGettingStartedRoute
  '/guides/security': typeof GuidesSecurityRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/trading/futures': typeof TradingFuturesRoute
  '/trading/spot': typeof TradingSpotRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/trading/': typeof TradingIndexRoute
  '/api/public/admin/delete': typeof ApiPublicAdminDeleteRoute
  '/api/public/admin/register': typeof ApiPublicAdminRegisterRoute
  '/api/public/admin/update': typeof ApiPublicAdminUpdateRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/admin'
    | '/app'
    | '/assets'
    | '/auth'
    | '/faq'
    | '/policies'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/administrator'
    | '/admin/customer-service'
    | '/admin/dashboard'
    | '/admin/deposit-requests'
    | '/admin/financial-status'
    | '/admin/futures'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/ownership'
    | '/admin/sample-tokens'
    | '/admin/spot-control'
    | '/admin/support'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/app/assets'
    | '/app/earn'
    | '/app/faq'
    | '/app/futures'
    | '/app/home'
    | '/app/market'
    | '/app/policies'
    | '/app/settings'
    | '/app/spot'
    | '/app/terms'
    | '/app/trade-fi'
    | '/guides/fees'
    | '/guides/getting-started'
    | '/guides/security'
    | '/markets/$symbol'
    | '/trading/futures'
    | '/trading/spot'
    | '/admin/'
    | '/app/'
    | '/guides/'
    | '/markets/'
    | '/trading/'
    | '/api/public/admin/delete'
    | '/api/public/admin/register'
    | '/api/public/admin/update'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/assets'
    | '/auth'
    | '/faq'
    | '/policies'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/administrator'
    | '/admin/customer-service'
    | '/admin/dashboard'
    | '/admin/deposit-requests'
    | '/admin/financial-status'
    | '/admin/futures'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/ownership'
    | '/admin/sample-tokens'
    | '/admin/spot-control'
    | '/admin/support'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/app/assets'
    | '/app/earn'
    | '/app/faq'
    | '/app/futures'
    | '/app/home'
    | '/app/market'
    | '/app/policies'
    | '/app/settings'
    | '/app/spot'
    | '/app/terms'
    | '/app/trade-fi'
    | '/guides/fees'
    | '/guides/getting-started'
    | '/guides/security'
    | '/markets/$symbol'
    | '/trading/futures'
    | '/trading/spot'
    | '/admin'
    | '/app'
    | '/guides'
    | '/markets'
    | '/trading'
    | '/api/public/admin/delete'
    | '/api/public/admin/register'
    | '/api/public/admin/update'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/admin'
    | '/app'
    | '/assets'
    | '/auth'
    | '/faq'
    | '/policies'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/administrator'
    | '/admin/customer-service'
    | '/admin/dashboard'
    | '/admin/deposit-requests'
    | '/admin/financial-status'
    | '/admin/futures'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/ownership'
    | '/admin/sample-tokens'
    | '/admin/spot-control'
    | '/admin/support'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/app/assets'
    | '/app/earn'
    | '/app/faq'
    | '/app/futures'
    | '/app/home'
    | '/app/market'
    | '/app/policies'
    | '/app/settings'
    | '/app/spot'
    | '/app/terms'
    | '/app/trade-fi'
    | '/guides/fees'
    | '/guides/getting-started'
    | '/guides/security'
    | '/markets/$symbol'
    | '/trading/futures'
    | '/trading/spot'
    | '/admin/'
    | '/app/'
    | '/guides/'
    | '/markets/'
    | '/trading/'
    | '/api/public/admin/delete'
    | '/api/public/admin/register'
    | '/api/public/admin/update'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AssetsRoute: typeof AssetsRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  PoliciesRoute: typeof PoliciesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  GuidesFeesRoute: typeof GuidesFeesRoute
  GuidesGettingStartedRoute: typeof GuidesGettingStartedRoute
  GuidesSecurityRoute: typeof GuidesSecurityRoute
  MarketsSymbolRoute: typeof MarketsSymbolRoute
  TradingFuturesRoute: typeof TradingFuturesRoute
  TradingSpotRoute: typeof TradingSpotRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
  TradingIndexRoute: typeof TradingIndexRoute
  ApiPublicAdminDeleteRoute: typeof ApiPublicAdminDeleteRoute
  ApiPublicAdminRegisterRoute: typeof ApiPublicAdminRegisterRoute
  ApiPublicAdminUpdateRoute: typeof ApiPublicAdminUpdateRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administrator': {
      id: '/admin/administrator'
      path: '/administrator'
      fullPath: '/admin/administrator'
      preLoaderRoute: typeof AdminAdministratorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer-service': {
      id: '/admin/customer-service'
      path: '/customer-service'
      fullPath: '/admin/customer-service'
      preLoaderRoute: typeof AdminCustomerServiceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposit-requests': {
      id: '/admin/deposit-requests'
      path: '/deposit-requests'
      fullPath: '/admin/deposit-requests'
      preLoaderRoute: typeof AdminDepositRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financial-status': {
      id: '/admin/financial-status'
      path: '/financial-status'
      fullPath: '/admin/financial-status'
      preLoaderRoute: typeof AdminFinancialStatusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/futures': {
      id: '/admin/futures'
      path: '/futures'
      fullPath: '/admin/futures'
      preLoaderRoute: typeof AdminFuturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ownership': {
      id: '/admin/ownership'
      path: '/ownership'
      fullPath: '/admin/ownership'
      preLoaderRoute: typeof AdminOwnershipRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sample-tokens': {
      id: '/admin/sample-tokens'
      path: '/sample-tokens'
      fullPath: '/admin/sample-tokens'
      preLoaderRoute: typeof AdminSampleTokensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/spot-control': {
      id: '/admin/spot-control'
      path: '/spot-control'
      fullPath: '/admin/spot-control'
      preLoaderRoute: typeof AdminSpotControlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/earn': {
      id: '/app/earn'
      path: '/earn'
      fullPath: '/app/earn'
      preLoaderRoute: typeof AppEarnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faq': {
      id: '/app/faq'
      path: '/faq'
      fullPath: '/app/faq'
      preLoaderRoute: typeof AppFaqRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/futures': {
      id: '/app/futures'
      path: '/futures'
      fullPath: '/app/futures'
      preLoaderRoute: typeof AppFuturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/policies': {
      id: '/app/policies'
      path: '/policies'
      fullPath: '/app/policies'
      preLoaderRoute: typeof AppPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spot': {
      id: '/app/spot'
      path: '/spot'
      fullPath: '/app/spot'
      preLoaderRoute: typeof AppSpotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/terms': {
      id: '/app/terms'
      path: '/terms'
      fullPath: '/app/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trade-fi': {
      id: '/app/trade-fi'
      path: '/trade-fi'
      fullPath: '/app/trade-fi'
      preLoaderRoute: typeof AppTradeFiRouteImport
      parentRoute: typeof AppRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/fees': {
      id: '/guides/fees'
      path: '/guides/fees'
      fullPath: '/guides/fees'
      preLoaderRoute: typeof GuidesFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/getting-started': {
      id: '/guides/getting-started'
      path: '/guides/getting-started'
      fullPath: '/guides/getting-started'
      preLoaderRoute: typeof GuidesGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/security': {
      id: '/guides/security'
      path: '/guides/security'
      fullPath: '/guides/security'
      preLoaderRoute: typeof GuidesSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$symbol': {
      id: '/markets/$symbol'
      path: '/markets/$symbol'
      fullPath: '/markets/$symbol'
      preLoaderRoute: typeof MarketsSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/': {
      id: '/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof TradingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/futures': {
      id: '/trading/futures'
      path: '/trading/futures'
      fullPath: '/trading/futures'
      preLoaderRoute: typeof TradingFuturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/spot': {
      id: '/trading/spot'
      path: '/trading/spot'
      fullPath: '/trading/spot'
      preLoaderRoute: typeof TradingSpotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/delete': {
      id: '/api/public/admin/delete'
      path: '/api/public/admin/delete'
      fullPath: '/api/public/admin/delete'
      preLoaderRoute: typeof ApiPublicAdminDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/register': {
      id: '/api/public/admin/register'
      path: '/api/public/admin/register'
      fullPath: '/api/public/admin/register'
      preLoaderRoute: typeof ApiPublicAdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/update': {
      id: '/api/public/admin/update'
      path: '/api/public/admin/update'
      fullPath: '/api/public/admin/update'
      preLoaderRoute: typeof ApiPublicAdminUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdministratorRoute: typeof AdminAdministratorRoute
  AdminCustomerServiceRoute: typeof AdminCustomerServiceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepositRequestsRoute: typeof AdminDepositRequestsRoute
  AdminFinancialStatusRoute: typeof AdminFinancialStatusRoute
  AdminFuturesRoute: typeof AdminFuturesRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOwnershipRoute: typeof AdminOwnershipRoute
  AdminSampleTokensRoute: typeof AdminSampleTokensRoute
  AdminSpotControlRoute: typeof AdminSpotControlRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministratorRoute: AdminAdministratorRoute,
  AdminCustomerServiceRoute: AdminCustomerServiceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepositRequestsRoute: AdminDepositRequestsRoute,
  AdminFinancialStatusRoute: AdminFinancialStatusRoute,
  AdminFuturesRoute: AdminFuturesRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOwnershipRoute: AdminOwnershipRoute,
  AdminSampleTokensRoute: AdminSampleTokensRoute,
  AdminSpotControlRoute: AdminSpotControlRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppEarnRoute: typeof AppEarnRoute
  AppFaqRoute: typeof AppFaqRoute
  AppFuturesRoute: typeof AppFuturesRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMarketRoute: typeof AppMarketRoute
  AppPoliciesRoute: typeof AppPoliciesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpotRoute: typeof AppSpotRoute
  AppTermsRoute: typeof AppTermsRoute
  AppTradeFiRoute: typeof AppTradeFiRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppEarnRoute: AppEarnRoute,
  AppFaqRoute: AppFaqRoute,
  AppFuturesRoute: AppFuturesRoute,
  AppHomeRoute: AppHomeRoute,
  AppMarketRoute: AppMarketRoute,
  AppPoliciesRoute: AppPoliciesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpotRoute: AppSpotRoute,
  AppTermsRoute: AppTermsRoute,
  AppTradeFiRoute: AppTradeFiRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AssetsRoute: AssetsRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  PoliciesRoute: PoliciesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  GuidesFeesRoute: GuidesFeesRoute,
  GuidesGettingStartedRoute: GuidesGettingStartedRoute,
  GuidesSecurityRoute: GuidesSecurityRoute,
  MarketsSymbolRoute: MarketsSymbolRoute,
  TradingFuturesRoute: TradingFuturesRoute,
  TradingSpotRoute: TradingSpotRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  MarketsIndexRoute: MarketsIndexRoute,
  TradingIndexRoute: TradingIndexRoute,
  ApiPublicAdminDeleteRoute: ApiPublicAdminDeleteRoute,
  ApiPublicAdminRegisterRoute: ApiPublicAdminRegisterRoute,
  ApiPublicAdminUpdateRoute: ApiPublicAdminUpdateRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
