// This file is automatically generated. Do not edit it directly.

// On a Lovable preview surface, broker the auth session to the editor over
// postMessage so the project's preview surfaces share one login; else localStorage.
export function brokeredPreviewStorage() {
  if (typeof window === 'undefined') return undefined;
  // Auth storage must be synchronous and local to the app origin. Waiting on the
  // editor's postMessage broker while GoTrue holds its auth lock can prevent a
  // credential request from ever starting in an embedded preview. localStorage
  // is persistent, isolated by origin, and is also what published apps use.
  return localStorage;
}
